NumberCount2/Controllers/NumberCountController.cs
using System;
// using System.Net.Http;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Text.Encodings.Web;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.WebUtilities;
using NumberCount2.Model;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace NumberCount2.Controllers
{
    public class NumberCountController : Controller
    {
        public string upto { get; set; }

        /// <summary>
        /// GET: /NumberCount/
        /// This is an HTTP GET method that is invoked by appending "/NumberCount/" to the base URL.
        /// This method returns a View object. It uses a view template to generate an HTML response
        /// to the browser. Controller methods (also known as action methods) such as the Index method
        /// generally return an IActionResult (or a class derived from ActionResult), not primitive
        /// types like string.
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            return View();
        }

        //
        // GET: /NumberCount/DefaultAction/
        // This is an HTTP GET method that is invoked by appending "/NumberCount/DefaultAction" to the base URL.
        public string DefaultAction()
        {
            string message = "This is the default action method.\n"
                + "It is also the action method you get when you add \"NumberCount\" or \"NumberCount/DefaultAction\" to the URL.\n"
                + "Try also \"FutureAction\"!";
            return message;
        }
        public IActionResult Result()
        {
            HandleUserInteraction();
            return View();
        }

        private void HandleUserInteraction()
        {
            short lowerLimit, upperLimit;
            string u2 = "";
            NumberSeries numbers = null;
            HttpRequest uri = HttpContext.Request;
            QueryString query = uri.QueryString;
            var queryDictionary = QueryHelpers.ParseQuery(query.ToString());  // System.Web cannot be used in .NET Core. Had to rewrite using Microsoft.AspNetCore.WebUtilities.

            ViewData["success"] = "false";
            if (queryDictionary.ContainsKey("upto"))
            {
                u2 = queryDictionary["upto"];
                ViewData["UpperLimit"] = u2;
            }

            lowerLimit = 1;
            if (Int16.TryParse(u2, out upperLimit))
            {
                upperLimit = Int16.Parse(u2);
                if (upperLimit >= lowerLimit)
                {
                    numbers = new NumberSeries(upperLimit);
                    ViewData["1"] = numbers.Count(1);
                    ViewData["2"] = numbers.Count(2);
                    ViewData["3"] = numbers.Count(3);
                    ViewData["4"] = numbers.Count(4);
                    ViewData["5"] = numbers.Count(5);
                    ViewData["6"] = numbers.Count(6);
                    ViewData["7"] = numbers.Count(7);
                    ViewData["8"] = numbers.Count(8);
                    ViewData["9"] = numbers.Count(9);
                    ViewData["0"] = numbers.Count(0);
                    ViewData["success"] = "true";
                }
            }

            return;
        }
    }
}

NumberCount2/Views/NumberCount/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "NumberCount Index page";
}
<form id="form" action="/NumberCount/Result">
    Count the digits used to write numbers from 1 to
    <!-- Ø{<input asp-for="upto">}.<br /> -->
    <input id="upper" name="upto">.<br />

    <!-- <button type="submit" onclick="location.href='ØUrl.Action("Index", "NumberCount")'">Calculate</button> -->
    <button type="submit">Calculate</button>
</form>

NumberCount2/Views/NumberCount/NumberCountMenu.cshtml
<!DOCTYPE html>
@* NumberCountMenu View Template.
    Defines the layout for all MVC views in the application.
*@
@{
    ViewData["Title"] = "Let's play";
}
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] NumberCount!</title>
        <environment names="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
            <link rel="stylesheet" href="~/css/site.css" />
        </environment>
        <environment names="Staging,Production">
            <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
            <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        </environment>
    </head>
    <body>
        <h2>NumberCount</h2>
        @* By default, every layout must call RenderBody . Wherever the call to RenderBody is placed, the contents of the selected cshtml view will be rendered. *@
        @RenderBody()
        <div id="footer">
            <p>You are running the application "NumberCount".</p>
            <p>To restart the UI, replace everything after the port number in the URL with "<a href="../Index">/Index</a>".</p>
        </div>
    </body>
</html>

NumberCount2/Views/NumberCount/Result.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "NumberCount Result page";
}
<div class="centered_text">
    @if (ViewData["success"].Equals("true"))
    {
        @:<p>To write the numbers from 1 to @ViewData["UpperLimit"], you need:</p>
        @:<div id="list"><ul id="ul"><li>@ViewData["1"] '1's</li><li>@ViewData["2"] '2's</li><li>@ViewData["3"] '3's</li><li>@ViewData["4"] '4's</li><li>@ViewData["5"] '5's</li>
        @:<li>@ViewData["6"] '6's</li><li>@ViewData["7"] '7's</li><li>@ViewData["8"] '8's</li><li>@ViewData["9"] '9's</li><li>@ViewData["0"] '0's</li></ul></div>
    }
    else
    {
        @:<p>"@ViewData["UpperLimit"]" is not a valid number.</p>
    }

    <a href="/NumberCount/Index"><input name="register" type="submit" id="button0" value="Back"></a>
</div>